volumes:
  postgres_data:
  static_value:
  media_value:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_value:/backend_static
      - media_value:/app/media/
    depends_on:
      - db
  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - static_value:/app/result_build/build
  nginx:
    build: ./infra/
    ports:
      - "80:80"
    volumes:
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - frontend
      - backend